### ISSUE TITLE
Default icons on a Mac

### ISSUE THREAD

**Issue by locovna** [joshavanier/log#11]
Do the icons (the blue one) supposed to be like this?
<img width="344" alt="screen shot 2017-11-05 at 20 24 09" src="https://user-images.githubusercontent.com/15370225/32417796-8b2ea6e6-c267-11e7-8721-3c004734a753.png">
<img width="124" alt="screen shot 2017-11-05 at 20 24 42" src="https://user-images.githubusercontent.com/15370225/32417797-8b4e87ea-c267-11e7-8150-cedcaad053e0.png">
I have downloaded `log-0.1.1-mac-x64.zip 48 MB` version from itch.io

**Comment by thmnmlist** [comment]
They're characters but rendered as emoji, you can use `set icons false`. Same on Windows #2

**Comment by locovna** [comment]
Sorry, didn't notice the similar issue. One icon is still here after  `set icons false`, nearby main timer. It's not big deal, anyway.
Thank you for your logger

**Comment by joshavanier** [comment]
The next update will get rid of those Unicode icons (until I find a proper set).

By the way, @locovna are you on High Sierra? Are you also experiencing issues where the app window goes blank after typing in commands?

**Comment by locovna** [comment]
thanks!
I am on Sierra (not new) 10.12.6, yes, there is such issue. After every command, whole app screen goes dark-gray. Looks like it's updating or something

**Comment by joshavanier** [comment]
@locovna I'm pushing an update that should fix that. It will be up soon :)

**Comment by locovna** [comment]
just updated the app and:
_app window goes blank after typing in commands_ - gone, thanks!
timer icon does not appear - thanks!
and thank you for the Statics in the guide as well.

**Comment by locovna** [comment]
But I tried `set icons true` -- works, after that `set icons false` -- doesn't. So now I'm not able to switch to the text mode. I have tried to reinstall the app, but nothing seems to happen. Other commands work

**Comment by joshavanier** [comment]
I don't know what's happening with `set icons`. In the meantime, what you can do is `export` and manually edit the exported JSON file (set icons to false, that should be in line 7) and then save and import that file again. Remember to use absolute paths though when you run import

`import /home/location/to/yourfile.json` and not just `import yourfile.json`
