### ISSUE TITLE
Can't import data

### ISSUE THREAD

**Issue by thmnmlist** [joshavanier/log#12]
I just downloaded new version and directly opened without changing anything, (I've prepared my own .json file somewhere else). This is the screen and I'm not able to write command to import new file
![screenshot](https://user-images.githubusercontent.com/17025246/32457759-363db31e-c33b-11e7-829e-be85f0bd1495.PNG)

**Comment by locovna** [comment]
@thmnmlist 
I guess this might "help"
https://joshavanier.itch.io/log/devlog/14563/013-readme

**Comment by joshavanier** [comment]
This is my bad. I should have specified: use absolute paths, not relative.
`import /home/folder/location/to/file.json`

**Comment by thmnmlist** [comment]
@spncryn thanks a lot, already read that but the problem is a bit different
@joshavanier not your bad, you explained well enough in readme file

But when I open the log I see that screen above and I'm not able to write any command, I mean the console bar doesn't appear (also tried to just write in case if it doesn't show but it works). If I can, I'll just copy my .json file into folder and import it

**Comment by joshavanier** [comment]
Forgot to close this. [1.0.1](https://joshavanier.github.io/log/) has better import/export :)
