### ISSUE TITLE
[Suggestion] Common shortcuts for Mac

### ISSUE THREAD

**Issue by locovna** [joshavanier/log#14]
Default shortcut for minimize/hide app window doesn't work (`Command-M` or `Command-H`)
Sorry, I don't really know if such behavior should be inherited by default because it is mac app or implemented by hand. But in my experience `Command-M` works for every app.
Shortcut for quit `Command-Q` is working

https://support.apple.com/en-us/HT201236
<img width="957" alt="screen shot 2017-11-06 at 22 50 37" src="https://user-images.githubusercontent.com/15370225/32463572-ebd1c184-c345-11e7-8b8a-c340af2aad46.png">

**Comment by locovna** [comment]
And there are no buttons(like, for example on right app) for this
<img width="285" alt="screen shot 2017-11-06 at 23 02 55" src="https://user-images.githubusercontent.com/15370225/32463881-bcb77e10-c346-11e7-834b-787608a95838.png">

**Comment by joshavanier** [comment]
Ahhh. I forgot about this; I'm sorry. University life weighs down heavily on me hehe. Unfortunately, I don't have a macOS machine to test with so I'm going to need help with implementing macOS shortcuts.

As for the window buttons, that's requires further discussion I guess. It was a deliberate design decision to not have window borders. Once the macOS shortcuts are working, then this shouldn't be a problem :)
