### ISSUE TITLE
[Issue] Case sensitivity

### ISSUE THREAD

**Issue by Godje** [joshavanier/log#15]
Even though you have `text-transform: uppercase` the projects are still case-sensitive, hence counted as different projects, although they are the same thing. In the first case I had to be Driving **L**icense and in the second case it was Driving **l**icense.

![image](https://user-images.githubusercontent.com/12803956/32478384-55b0990c-c339-11e7-8814-5dbd4d87e0f2.png)

**Comment by joshavanier** [comment]
The `text-transform: uppercase` is meant for the display only. In the log data, they will be considered two separate projects. I will patch this; thanks for the heads up. :)

Also: are you on 0.1.3 already?

**Comment by joshavanier** [comment]
1.0 lets you edit entries :)

**Comment by Godje** [comment]
@joshavanier oh so you did a first release 1.0 :)
Congrats on that!
Yeah I have been on 0.1.3 at that point. If the issue is resolved in the new version, then thank you!
