### ISSUE TITLE
[Suggestion] Make it more clear when a command succeded 

### ISSUE THREAD

**Issue by Flaque** [joshavanier/log#16]
It's hard to tell when a command was entered correctly and actually started the timer. 

Maybe add a green flash by the background of the command line? Maybe clear the console when you press enter? 

Thanks so much, love the app <3

**Comment by locovna** [comment]
+++

**Comment by joshavanier** [comment]
Yeah sorry about that. I wasn't aware of the console not clearing upon command entry. On Linux (what I use), it works alright. I don't have a way to test on Windows or macOS, unfortunately.

**Comment by Flaque** [comment]
If I get some time, I cant take a look at it if you're accepting PR's <3

**Comment by joshavanier** [comment]
PR's are welcome :)

**Comment by Godje** [comment]
I use the app on Windows and Linux and my console clears up effectively. Although I would really like some kind of indicator about the timer being started. Top-border slide-in notification on the gray/green background saying:

"Task timer `<name>` has started!"

or something close to that.

**Comment by joshavanier** [comment]
I'm still working on that. I used to have this feature where the whole screen shows a timer and what activity is being logged. It was removed because I couldn't decide on the design haha. I'm thinking of bringing it back.

https://twitter.com/joshavanier/status/926092656983252992

**Comment by joshavanier** [comment]
Notifications now appear when entries are started and ended
