### ISSUE TITLE
[Suggestion] shortcut to change tabs 

### ISSUE THREAD

**Issue by EduardoHi** [joshavanier/log#17]
First of all, I wanna congratulate you(@joshavanier) for your amazing program ! I was trying it out, and it's awesome.

It would be nice to change tab with <kbd>ctrl</kbd> + <kbd>tab</kbd> to the right and <kbd>ctr</kbd> + <kbd>shift</kbd> + <kbd>tab</kbd> to the left, I was trying to implement it but the `tab(s, g, t, v = false)` function is hard for me to understand. How can I Implement it?

for extra info, the conditions to the keydown event would be:

<- `e.ctrlKey && e.shiftKey && e.keyCode == 9`
and
-> `e.ctrlKey && e.shiftKey`

**Comment by joshavanier** [comment]
I'm currently rewriting Log's code to make it more understandable. The `tab()` function is universal. It applies to the main tabs (Overview, Details, etc.) as well as the sections within the Details section (Summary, Sectors, Projects). I like the idea of tab navigation via keyboard though :)

**Comment by joshavanier** [comment]
Wow this is really late lol. Been busy with school in the past few weeks. I just pushed a commit that adds keyboard navigation through tabs. ```Tab``` cycles through the tabs. I can't get ```Shift``` + ```Tab``` to work though for some reason.
