### ISSUE TITLE
Stacking logs (several starts in a row, or several end in a row) has weird behavior

### ISSUE THREAD

**Issue by ashtrail** [joshavanier/log#18]
I just started using the software and without realising it started several logs in a row (so multiple `start` before any `end`).

This creates logs with a start timestamp but no end timestamp.

Since it was possible to start several logs in a row (I don't think that should be allowed though) I thought if I did several `end` in a row they would 'close' the logs before, but it just updates the duration of the last entrie. This gives 'orhpan' logs that have a start timestamp but don't and will never have any end timestamp.

https://i.imgur.com/T64D7wa.png

Just to be sure what I'm saying is clear I will use the screenshot as an exemple : 

- I create a log with the command `start test1; test1; test1`
- I create another log, before ending the first : `start test2; test2; test2` (I think the software should just say "you are already in a log" or just do nothing instead of creating another one though)
- I `end` once, this ends test1
- I `end` a second time thinking it will end test2, but instead it just updates test1 end time and duration

**Comment by joshavanier** [comment]
Ah yeah. Multiple logs were not in mind when I created this system. I'll patch this. Thanks

**Comment by joshavanier** [comment]
This issue should now be fixed with the [1.0.1](https://joshavanier.github.io/log/) update :)
