### ISSUE TITLE
Many entries are added when I start and end only one task

### ISSUE THREAD

**Issue by lucleray** [joshavanier/log#20]
Hi,

I would love to try to use log to track my time but I am having an issue.

When I type `start hello1,hello2,hello3` and then `end` , I get that :

<img width="963" alt="capture d ecran 2017-11-29 a 16 05 21" src="https://user-images.githubusercontent.com/6616955/33364444-715d376c-d51f-11e7-824e-591d7216386e.png">

I am not sure why it's happening. Any idea ?

Thanks !

**Comment by lucleray** [comment]
I'm on macOS Sierra.

I started log with `npm start` and it works fine.

**Comment by joshavanier** [comment]
If you built it from source, would you mind checking the console if there are any errors? I'm on Linux and I've never gotten this duplication issue. I'm also busy these days with final exams coming up so I'll look into this when I get back

**Comment by lucleray** [comment]
I built it from source.
I think it reset the entries file and now everything is working, both the built from source version and the packaged version.

**Comment by Godje** [comment]
I am not sure if that is the case, because I didn't check the parsing function in the new update.
But it might be because you don't have the spaces between your entries.

**Comment by joshavanier** [comment]
I haven't packaged 1.0.1, but I pushed a few changes in the repo that should fix some of the issues with 1.0.0. I'll update the itch.io files as soon as I can
