### ISSUE TITLE
[Bug] Broken console.log

### ISSUE THREAD

**Issue by FranzSkuffka** [joshavanier/log#22]
Repo cloned from master.
![image](https://user-images.githubusercontent.com/7485959/34087469-98d9a5cc-e3a3-11e7-9f20-8a917825ff78.png)

**Comment by joshavanier** [comment]
Fixed. Sorry about that

**Comment by FranzSkuffka** [comment]
All good <3 That was prompt.

**Comment by montogeek** [comment]
Hi!
I just cloned master and got the same error:
![image](https://user-images.githubusercontent.com/1002461/34723751-f3551112-f54b-11e7-8fcc-551fab3c7cfa.png)

**Comment by montogeek** [comment]
After debugging I get `isEmpty(user.log) === true`, then it evaluates the second part of the expression that uses log

**Comment by joshavanier** [comment]
Oops. My bad. Thanks for bringing it up. Be careful if you use Log straight from the repo; it's not exactly stable here hehe
