### ISSUE TITLE
Improve duration format

### ISSUE THREAD

**Issue by FranzSkuffka** [joshavanier/log#23]
![screen shot 2017-12-18 at 11 40 31](https://user-images.githubusercontent.com/7485959/34102173-6bcf2bac-e3e8-11e7-898a-681eb30c2bdd.png)

Expected: 10 min / 25 min

**Comment by joshavanier** [comment]
That is correct. 0.17 means 0.17 of an hour which is roughly 10 minutes. 0.5 = 30 minutes. I will add a more intuitive readable format if you like. Something like these:

```1h 25m```, ```10m```, etc.

**Comment by FranzSkuffka** [comment]
Thanks for the clarification - I will adjust the title.

**Comment by joshavanier** [comment]
Thank you for your suggestions. Keep them coming :)

**Comment by FranzSkuffka** [comment]
I think it's enough if you add an `h` afterwards.

I'm thinking about PRing the pomodoro timer.

I did this one here, it's a super old project though:
http://pomodo.netlify.com/

What I really need in a pomodoro times is that it keeps running, I don't have to press anything before going back to work or starting a break.

**Comment by joshavanier** [comment]
I've just implemented window notifications upon starting log entries. We could use it for Pomodoro to prompt users to take breaks/continue working.

From how I understand it, and do correct me if I'm wrong, you want the log entry to stop or pause automatically when it's time for a break and resume when you get back?

**Comment by FranzSkuffka** [comment]
1. That would be a good idea.

2. No, I was not referring to log.

I just wanted to explain why I wrote my own timer. I need the timer to run without me having any hassle with it so I can focus on work. If you have to manually activate the timer it's easy to miss it out and then you work without the timer reminding you just because it does not run.

Also I think it's super simple and easy to use while fitting log's style somewhat.

**Comment by joshavanier** [comment]
I'm closing this issue. The upcoming 1.0.2 update clarifies the duration format. If you're still up to the task of adding a Pomodoro timer, be my guest :)

**Comment by FranzSkuffka** [comment]
Cool & Thx.

To be clear: I'm not really using log at the moment, please don't rely on my contribution here. I really like the project though. I think I will tune in now & then.
