### ISSUE TITLE
[Issue] Cannot start anything after importing a log

### ISSUE THREAD

**Issue by Godje** [joshavanier/log#24]
I have finally downloaded the app through the itch.io program. I don't feel like it matters anyways.
Launching the program was fine. But how did the program retrieve my previous files?
I wanted to clear every log happened and start over.
I exported a log.
I just removed the objects. Only the objects inside the array.
I imported the .json file back into the program.
And now nothing works. I can't start any logs anymore. I tried reinstall and doing all the other possible things. Nothing solved the problem.
How Do I enter the Developer Console, so I can see the error readout or something. Because upon hitting 'Enter' with the full start command inside - nothing happens.

**Comment by joshavanier** [comment]
Sorry, my bad. I wrote something that accidentally disabled input if the user has no data. I need to be more thorough with testing (especially with testing for new user scenarios).

I'm pushing 1.0.2 now; it should be up soon. :)

**Comment by Godje** [comment]
You can close the issue now. The issue is resolved from what I see.
