### ISSUE TITLE
[Suggestion] Manually add log entries

### ISSUE THREAD

**Issue by benjamin-rood** [joshavanier/log#27]
Add an `add` function which allows you to specify the `sector | project | description | date | start time | end time` as a console command.

Useful if you forgot to use the app.

I can write the necessary code for you, I just thought I would suggest it first before doing so.

**Comment by joshavanier** [comment]
Yeah sure that'd be nice. For now the work-around for such scenarios are to edit the timestamps but that requires an existing entry. I'm currently working on a few other projects this weekend so if you'd like to write it, feel free to do so. Otherwise, I'll get back to this around Monday :)
