### ISSUE TITLE
[Suggestion] Use an SPA framework.

### ISSUE THREAD

**Issue by FranzSkuffka** [joshavanier/log#33]
The current architecture is quite clean but will grow out of hand soon.

I have experience with React, Vue, Angular and Elm. I would definitely opt for Elm as it provides the best dev experience in my opinion. VueJS would also be a great pick.

**Comment by joshavanier** [comment]
Hmm. I don't know about that. I'm not a big fan of using frameworks as they often have features that aren't needed and they just have to be there. That goes for Electron too lol that's why I'm creating a CLI version of Log.

But I am open to trying them out, if it becomes necessary at some point. I might go with React Native for a future project to create a mobile app for Log

**Comment by FranzSkuffka** [comment]
Sure, frameworks bring a lot of stuff you often don't need. However they also help you find a common pattern for your problems and keep you from reinventing the Wheel.

You can export functionality from the current code base and reuse it in the cli with JS modules.

If you don't like frameworks I suggest developing a pwa rather than a hybrid app...

**Comment by joshavanier** [comment]
Reinventing the wheel isn't always a bad thing though. I'd rather build a custom framework specifically designed to suit the project's needs and nothing more. The only real downside of that is time consumption.

Side note: I found an alternative to React -- https://preactjs.com/

**Comment by FranzSkuffka** [comment]
I'm actually also opposed to frameworks - I never used jquery (it's actually a lib) because most can be done with CSS. Angular also was too large and monolithic for me. React / Inferno / Preact are all just _view_ libraries. They do one thing - quite well. A framework is a view library + state management + opinionated structures + utilities. I think the title of this thread is not on point. I try to point out that there is probably some functionality in Log that can be perfectly covered using an existing solution without any downsides.

I think building a custom framework is a great idea from your perspective. However I believe we do not share our opinion on _why_ that is. It will give you a whole lot of experience. But a custom framework is afterall a framework that new contributors will need to learn. Security issues must be covered, etc etc etc. You may consider this only as time consuming. However, a wise or not so wise framework choice heavily impacts a products longevity.

Log is slowly growing into a framework. That's great. I don't have the personal interest of moving this into any particular direction. I think it's a cool thing and I like to support the community, including you :) Thanks for you time!

**Comment by Godje** [comment]
The only issue I can find with NOT using a framework is the fact that the codebase will expand into its own framework that every contributor will have to learn. 
Preact will do the job well, and I think that size of the framework doesn’t matter at all when you talk about an Electron application.
When you write in [p]react there is enough people who can help you. But if you build a custom framework that will do literally the same thing, not all the people will take on learning a new API for the sake of a few contributions.

**Comment by nblackburn** [comment]
Not fussed either way but wanted to point out that React and Vue are not frameworks, they are UI libraries.
