### ISSUE TITLE
[Suggestions] - New, more comfortable way to create new entries.

### ISSUE THREAD

**Issue by Godje** [joshavanier/log#4]
Just brainstormed a bit about your `start` command.
So you enter a command `start` and there should be 3 strings following the command. Each element from this array of strings is now assigned to an object entry in log.js.
Why not make a better parsing for the command. Entering string symbols takes time. You could make a bit more parsing work, but some of these ways would probably be way more comfortable.

`start Entry : Entry : Entry`
`start Entry || Entry || Entry`
`start spaces_replaced_with_underscores no_strings_to_type just_spaces_between_entries.`

I wish I knew the difficulty of implementing any of these features. If you would have dev-docs I would try to contribute to this project =)

**Comment by joshavanier** [comment]
Another wonderful idea from you. I like it!  All of the app's functions are currently in one lengthy file (I should split them to make things easier). The start command is found here:

https://github.com/joshavanier/log/blob/b791c79b67967507bf2b18899acda8168487a79c/js/log.js#L177

**Comment by hoops-doggit** [comment]
Hey joshavanier I've been brainstorming how to go about making a program for myself which more or less does exactly what this does so I'd love to help out with development if I can. I know basic C# so I'm guessing learning 

I was just thinking something like what Godje was thinking as well but it would be great if there were even less characters if possible. Something easy to find that doesn't need shift key to access, something like:
`start sector/ project/ description`

**Comment by joshavanier** [comment]
@hoops-doggit, I love that. That will be way more efficient

**Comment by espy** [comment]
Good thread, just want to question some of the assumptions in it:
- `/` is reachable without the shift key -> not true for many keyboard layouts
- `/` or `:` will never be used by people as parts of the values of `sector`, `project` or `description` -> risky. I think `|` should be _relatively_ safe, but that saves very little in terms of keystrokes. 

String parsing is always fraught with peril in this regard, though. Someone somewhere has a legitimate reason to use `|` in a project name, and 💥 

Text-only interfaces are necessarily complicated and loaded with convention, one way to make it both accessible and pro-user friendly is to split each command that expects multiple arguments up into parts: `set⏎` triggers three consecutive labeled prompts, one for each argument (`Enter sector:`, `Enter project:`, `Enter description:`). That would be easily learnable, you could still use it blindly of you already know it, it’s faster than wrapping three arguments in double quotes, and the argument parsing is absolutely bulletproof by default. The one drawback is: there’s no obvious way to change the `sector` once you’ve entered it. Plus `esc` would need to be bound to cancel the whole thing.

The input component would be a lot more complicated, but you’d spend less time trying to make the fiddly string parsing work.

**Comment by joshavanier** [comment]
@espy, thank you for your suggestion. I just had an idea inspired by your concept. What if the input went something like this:

start <kbd>Tab</kbd> Type in sector name <kbd>Tab</kbd> Project title <kbd>Tab</kbd> Type in description

Everything will still be contained in the console bar but there will be three input boxes in a row. <kbd>Tab</kbd> and <kbd>Shift + Tab</kbd> can be used to move back and forth to fix any errors.

Additionally, an autofill or autocorrect-like feature could help streamline the input and may help minimise the risk of mistypes

**Comment by espy** [comment]
Aaaah, nice. I was thinking about tabbing for a bit too, since that’s the most natural interaction for switching inputs, but I got stuck somewhere :D Really clean solution! 👍 

Only problem: Now you’ll have to fight the command line purists :D 

Also, <kbd>These</kbd> <kbd>are</kbd> <kbd>nice</kbd>! Thanks, didn’t know GH could do that.

**Comment by hoops-doggit** [comment]
@espy @joshavanier , tabbing or enter are both great ideas. I was looking at my phones keyboard to see what symbols were accesible while typing letters (on android) and the only ones available were `.` and `,`.

Whichever method you choose to go with @joshavanier , it would be great if it was programmed in a way that is easily found and changed to suit personal preferance, as the data entry aspect will likely be the users most common interaction with the app.

PS I was looking at my cell phone keyboard because I would `love` to be able to use Log on a portable device

**Comment by joshavanier** [comment]
@hoops-doggit A mobile app is currently impossible for me as my computer is simply too weak for such development. I agree that having the ability to use the Log on a mobile device is very convenient and would love to make that a reality as soon as possible

**Comment by Godje** [comment]
@joshavanier 
it might need a different thread of Mobile App brainstorming. But.
If you will make the app for a Phone, it will need some kind of Account system. Because peopel would love to Log on the phone and then move to a computer for their own projects there. And syncing will be another stuff to tackle too. I think making a mobile app, while we are still fighting some issues with the Log app on it's main platform (PC) is unwise.

**Comment by joshavanier** [comment]
@Godje you're right. We'll set it aside for now.
