### ISSUE TITLE
[Suggestions] - Ability to set save location to external folder

### ISSUE THREAD

**Issue by hoops-doggit** [joshavanier/log#5]
It would be great if you could set and save a location to save the log to so that you can set somewhere like a dropbox/drive location etc so that you can edit data from multiple locations. 

We might be talking about the same thing where you're talking about remembering import location in the guide, in which case feel free to delete this suggestion.

**Comment by joshavanier** [comment]
I'm still trying to figure it out but I definitely need to simplify data storage and perhaps no longer require having to import with each future update. Hmm

**Comment by hoops-doggit** [comment]
I'm quite happy to help out, either with r&d or if you want to assign me a task I'd be happy to help out on bits you're not working on. I was brainstorming building a tool for myself that does exactly what Log does over the weekend so I'm 10000% happy to help out developing it.

**Comment by joshavanier** [comment]
I'll be busy with classes throughout November and half of December so I won't be as productive with Log development as much as I'd like. If you'd like to start somewhere, you may choose from this list. Although please note that someone is already taking up the task of creating app icons for Log.

https://github.com/joshavanier/log#to-do

Thank you for your interest in contributing! :)

**Comment by hoops-doggit** [comment]
Cool cool. Can do. I'll fork and let you know when I've finished something.

**Comment by kodedninja** [comment]
@joshavanier Don't forget to close this :)
