### ISSUE TITLE
Provide tagged releases here on GitHub

### ISSUE THREAD

**Issue by ahstro** [joshavanier/log#50]
It'd be nice if you provieded releases here on GitHub, for adding Log to things like the Arch Linux package manager

**Comment by joshavanier** [comment]
I don't have any experience with things like this. Does that mean if I push releases here, you'd be able to install it like `pacman -S log`? How does that work?

**Comment by ahstro** [comment]
Well, sort of. It means that there would be predictable, permanent URLs from which to download releases, so then someone could create a package for Arch Linux that would install the latest stable release instead of just pulling from GitHub like I'm doing [now](https://aur.archlinux.org/packages/log-git/)

**Comment by joshavanier** [comment]
Oh I see. That's pretty neat. Alright, well I'm still working on a few things but I'll be releasing a new version in a couple of days so just stand by for now. Thanks for creating the package

**Comment by Godje** [comment]
Make sure to not forget the 64bit linux version, just like it happened with
Qyllium on Itch.io

2018-05-11 10:01 GMT-07:00 Josh Avanier <notifications@github.com>:

**Comment by joshavanier** [comment]
All done :)
