### ISSUE TITLE
NaN if 0

### ISSUE THREAD

**Issue by Neko250** [joshavanier/log#55]
### Description

I often input entries manually after the work is done, so I just round the time, eg. 5 hours exactly.

Since I've updated to version `1.0.5`, entries with `00` string either on the hours or the minutes of the `human` stat format show `aN`. I suppose this is because, somewhere, something is evaluating as `NaN` (not a number) and then is being trimmed to match the 2 chars length of the field.

### Images

![entries](https://user-images.githubusercontent.com/2650578/40621781-9983712c-629e-11e8-9771-195cfbbe5e1f.png)

![edit](https://user-images.githubusercontent.com/2650578/40621784-9e4bb03e-629e-11e8-9c35-04c32cf4fd9c.png)

![log_2018-05-28_17-54-06](https://user-images.githubusercontent.com/2650578/40622113-2ef9e00a-62a0-11e8-97fe-67dd324d62b2.png)

**Comment by joshavanier** [comment]
Thanks for letting me know. I just fixed it and will include the patch in the next release. So how it worked was it took a number and split it at the decimal point: `1.6` would become `["1", "6"]` but `5.0` becomes only `["5"]` which made the second value `NaN` hehe
