### ISSUE TITLE
Showing NaN and Infinity on the overview screen

### ISSUE THREAD

**Issue by shahzeb1** [joshavanier/log#57]
![image](https://user-images.githubusercontent.com/1383831/41212026-04c61876-6cf0-11e8-91ba-02ab5dcc4d58.png)

Just installed log today. Really neat software. Just thought I'd drop in this bug report. It's likely an issue specific to brand new users. 

I'm willing to make this a pull request and fix it if you'd like.

**Comment by joshavanier** [comment]
It's already fixed here. I haven't updated itch.io yet
