### ISSUE TITLE
No console displays on macOS 10.14 (18A389)

### ISSUE THREAD

**Issue by gndclouds** [joshavanier/log#63]
Running Mac OS 10.14 (18A389)

When I launch log on macOS the console never appears anymore so I can't log anything.😱 Any suggestions?

**Comment by gndclouds** [comment]
Is there a way for me to completely remove the app and the reinstall it? System files and all?

**Comment by joshavanier** [comment]
Sorry to hear that! I hope you have backups. Unfortunately I have no means of testing anything on macOS. By default, Log creates a `log.json` in `~/Library/Application Support`. If you hadn't imported any existing log file, the app would read and write to that file. As for uninstalling it, I'm not too sure about that. Maybe deleting any related Log folder in `Application Support` would do the trick

**Comment by gndclouds** [comment]
That worked! Thanks!
