### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by dreyes-ias** [joshavanier/log#66]
Looks like there is a spelling error in the guide portion of the app. 'Customisation' should be 'Customization'.

**Comment by dreyes-ias** [comment]
<img width="955" alt="screen shot 2018-11-15 at 10 07 10 am" src="https://user-images.githubusercontent.com/41125738/48561607-4d1d5b80-e8be-11e8-9bf3-5b852f5875a8.png">

**Comment by joshavanier** [comment]
It's not an error. American English uses "customization" and I'm following British English. Note the word "optimise" in the rightmost panel. :)

**Comment by dreyes-ias** [comment]
@joshavanier haha oh good point, my apologies
