### ISSUE TITLE
Any instructions on how to contribute or where to chat (Discord)?

### ISSUE THREAD

**Issue by trivigy** [joshavanier/log#68]
I would love to see if I could contribute to this project. If there is no chat setup maybe I could setup Discord server, config, and update readme? @joshavanier

**Comment by joshavanier** [comment]
I'm not a fan of Discord but you can contact me on [Twitter](https://mobile.twitter.com/joshavanier) if you found bugs or have ideas for improvements :)

**Comment by trivigy** [comment]
Twitter is really inappropriate for sharing code snippets given the character limitation and no code highlighting. Especially when people have questions and want answers to their issues. I am happy to do slack or anything else of the same type if you have recommendations you like. Generally speaking though I tend to not concentrate on what I like but rather what others WILL find user friendly to ultimately contribute and use the product. The more people join, the more likely things to grow and be useful to a wider range of audience.

Also rather then just telling you about the ideas and filling up your time with more work, hoping flawlessly for you to do it, I figured I can just write the code and submit pull requests. This project has potential. I really like the simple user interface design. Input via scripts and output via gui. Brilliant.

**Comment by joshavanier** [comment]
I created a Slack workspace for this purpose and have sent you an invite (used the email on your GitHub profile). We'll see how it goes but for the meantime we can continue correspondence then.

I'm looking forward to hearing your thoughts on this. This project was one of my very first OSS projects and it's still a bit of a mess behind the scenes lol.

**Comment by trivigy** [comment]
This is for reference if anyone looks at this issue. https://discord.gg/Ger4sFs
Please make sure to join the conversation if you have any questions.
